version: 2

sources:
   - name: gz_raw_data
     schema: gz_raw_data
     description: greenweez raw data source 
     tables:
        - name: raw_gz_sales
          freshness:
            warn_after: 
              count: 90 
              period: day
          loaded_at_field: "CAST(date_date AS TIMESTAMP)"
          identifier: raw_gz_sales
          description: sales of greenweez / we have one row per products_id found in each orders_id.
          columns:
            - name: raw_gz_date_date
              description: the date of purchase
            - name: orders_id
              description: the order identifaction
            - name: products_id
              description: the product type
            - name: revenue
              description: the total revenue per order and product
            - name: quantity
              description: number of product
          tests: 
            - unique:
               column_name: "(orders_id || '_' || pdt_id)"
        - name: raw_gz_product
          identifier: raw_gz_product
          description: product type and price
          columns: 
            - name: products_id
              description: product model identification, PRIMARY KEY
              tests:
                 - unique
                 - not_null
            - name: purchase_price
              description: price of the product
        - name: raw_gz_ship
          identifier: raw_gz_ship
          description: ship costs, log costs, shipping fee
          columns:
            - name: orders_id
              description: identificatin of the orders, PRIMARY KEY
              tests: 
                - unique
                - not_null
            - name: shipping_fee
              description: fee for the shipping
            - name: logcost
              description: cost of logistic
            - name: ship_cost
              description: cost of shipping for the business
